%define TOK_PLUS    0
%define TOK_MINUS   1
%define TOK_STAR    2
%define TOK_SLASH   3
%define TOK_L_PAREN 4
%define TOK_R_PAREN 5
%define TOK_NUM     6
%define TOK_SPACE   7
%define TOK_DOT     8
%define TOK_OTHER   9
